language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install:
  - mysql -e 'create database firemind_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql firemind_test < test/base.sql
  - gem install bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - sleep 10
  - RAILS_ENV=test bin/rake db:migrate
services:
  - redis-server
