development:
  adapter: mysql2
  database: firemind_dev
  username: firemind
  password: 

test:
  adapter: mysql2
  database: firemind_test
  username: firemind
  password: 
  encoding: utf8

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: <%= ENV['DB_TIMEOUT'] || 5000 %>
